[project]
name = "inference-modules-vllm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <3.13"
dependencies = [
    "llm-jp-eval-inference",
    "torch>=2.10.0",
    "transformers>=5.1.0",
    "vllm>=0.17.0",
]

[tool.uv]
no-binary-package = ["pyairports"]

[tool.uv.sources]
llm-jp-eval-inference = { path = "../../", editable = true }
